import {readFileSync,writeFileSync} from 'node:fs';
export function addGameRules(input){
 input=input.replace('allow create: if grRulesReward(sid,entry);',"allow create: if request.resource.data.kind=='gameReward' && grRulesReward(sid,entry);").replace('allow update: if resource.data.amount==0 && grRulesReward(sid,entry);',"allow update: if request.resource.data.kind=='gameReward' && resource.data.amount==0 && grRulesReward(sid,entry);").replace('allow create: if rulesReward();',"allow create: if request.resource.data.kind=='taskReward' && rulesReward();").replace('allow update: if resource.data.amount == 0 && rulesReward();',"allow update: if request.resource.data.kind=='taskReward' && resource.data.amount == 0 && rulesReward();");
 if(input.includes('// Rules game protocol:'))return input.slice(0,input.indexOf('    // Rules game protocol:'))+readFileSync('integration/games/protocol.rules','utf8')+'\n  }\n}\n';
 let output=input.replace('    match /gameSessions/{session} {','    match /gameSessions/{session} {\n      allow create: if grSessionCreate(session);');
 output=output.replace("&& request.resource.data.completedAt == request.time;","&& request.resource.data.completedAt == request.time\n          && (resource.data.get('protocol','') != 'rules-game/1' || grSessionFinish(session,resource.data,request.resource.data));");
 output=output.replace("&& d.keys().hasOnly(['questionId','answer','correct','sequence','createdAt'])","&& d.keys().hasOnly(s.get('protocol','') == 'rules-game/1' ? ['questionId','answer','correct','sequence','createdAt','target','runStep'] : ['questionId','answer','correct','sequence','createdAt'])\n            && (s.get('protocol','') != 'rules-game/1' || grAnswerLinked(session,event,d))");
 output=output.replace('    match /coinAccounts/{sid}/entries/{entry} {','    match /coinAccounts/{sid}/entries/{entry} {\n      allow create: if request.resource.data.kind==\'gameReward\' && grRulesReward(sid,entry);\n      allow update: if request.resource.data.kind==\'gameReward\' && resource.data.amount==0 && grRulesReward(sid,entry);');
 return output.replace(/  }\s*}\s*$/,readFileSync('integration/games/protocol.rules','utf8')+'\n  }\n}\n');
}
if(process.argv.includes('--apply')){const file='integration/assessment/compatible.rules';writeFileSync(file,addGameRules(readFileSync(file,'utf8')));console.log('Added bounded Rules game protocol; existing permissions retained.');}
