import { useEffect, useState } from "react";
import { collection, doc, getDoc, getDocs, runTransaction } from "firebase/firestore";
import { db, OWNER_EMAIL } from "@/lib/firebase";
import { downloadCsv, parseAccountRoster, type AccountRosterRow } from "@/lib/csv";
import type { CloudProfile } from "@/contexts/StudentAccount";
type Entry={id:string;profile:CloudProfile};
type Access={email:string;studentId:string;enabled:boolean};
type Plan={row:AccountRosterRow;id:string;existing:boolean};
export default function AccountManager({onChanged}:{onChanged:()=>Promise<void>}){
 const [profiles,setProfiles]=useState<Entry[]>([]),[access,setAccess]=useState<Access[]>([]);
 const [csv,setCsv]=useState(""),[plan,setPlan]=useState<Plan[]>([]),[email,setEmail]=useState(""),[sid,setSid]=useState("");
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState("");const [revision,setRevision]=useState(0);
 async function refresh(){const [ps,acs,meta]=await Promise.all([getDocs(collection(db,"profiles")),getDocs(collection(db,"access")),getDoc(doc(db,"metadata","enrollment"))]);setProfiles(ps.docs.map(d=>({id:d.id,profile:d.data() as CloudProfile})));setAccess(acs.docs.map(d=>({email:d.id,...d.data()} as Access)));setRevision(meta.data()?.revision||0);}
 async function run(fn:()=>Promise<void>){setBusy(true);setNotice("");try{await fn();}catch(e){setNotice(e instanceof Error?e.message:"操作失敗");}finally{setBusy(false);}}
 useEffect(()=>{void run(refresh);},[]);
 function preview(){const rows=parseAccountRoster(csv);const ids=new Set<string>();const next=rows.map(row=>{if(row.email===OWNER_EMAIL)throw new Error("管理帳戶不能匯入為學生。");const binding=access.find(a=>a.email===row.email);const id=binding?.studentId || crypto.randomUUID();if(ids.has(id))throw new Error("兩個 email 對應同一名學生；名單只保留主要 email。");ids.add(id);return {row,id,existing:!!binding};});
   const effective=new Map(profiles.map(p=>[p.id,p.profile]));next.forEach(p=>effective.set(p.id,{...p.row,nickname:p.row.name.slice(0,20),avatar:"explorer",configured:false}));const identities=new Set<string>();for(const p of Array.from(effective.values())){const key=`${p.className}:${p.studentNo}`;if(identities.has(key))throw new Error(`${key} 已有其他學生紀錄；如屬同一人，請在下方連結 Gmail，勿另建紀錄。`);identities.add(key);}setPlan(next);
 }
 async function commit(){let expected=revision;let saved=0;try{for(let offset=0;offset<plan.length;offset+=100){const chunk=plan.slice(offset,offset+100);await runTransaction(db,async tx=>{const metaRef=doc(db,"metadata","enrollment");const meta=await tx.get(metaRef);if((meta.data()?.revision||0)!==expected)throw new Error("名單已被其他操作更新，請重新檢查匯入。");for(const item of chunk){const prior=profiles.find(p=>p.id===item.id)?.profile;const {email,...identity}=item.row;const profile:CloudProfile={...identity,nickname:prior?.nickname||identity.name.slice(0,20),avatar:prior?.avatar||"explorer",configured:prior?.configured||false};tx.set(doc(db,"profiles",item.id),profile);tx.set(doc(db,"access",email),{studentId:item.id,enabled:true});}tx.set(metaRef,{revision:expected+1});});expected++;saved+=chunk.length;}setNotice(`已匯入 ${saved} 人。學生登入後會自動帶出身分。`);setPlan([]);setCsv("");}catch(e){throw new Error(`已完成 ${saved} 人；${e instanceof Error?e.message:"未能完成"}。重新讀取名單後可重試。`);}finally{await refresh();await onChanged();}}
 async function link(email:string,studentId:string,enabled:boolean){await runTransaction(db,async tx=>{const ref=doc(db,"metadata","enrollment");const meta=await tx.get(ref);if((meta.data()?.revision||0)!==revision)throw new Error("名單已變更，請重新載入後再操作。");const profile=await tx.get(doc(db,"profiles",studentId));if(!profile.exists())throw new Error("學生紀錄不存在。");tx.set(doc(db,"access",email),{studentId,enabled});tx.set(ref,{revision:revision+1});});await refresh();setPlan([]);}
 return <section className="admin-panel mt-8 p-6"><h2 className="display-title text-2xl">學生帳戶名單</h2><p className="my-3">先匯入 email、班別、學號、姓名。學生只能選角色和暱稱，不能修改身分。學號 01 與 1 不同，請統一格式。</p>
 <div className="flex gap-3"><button className="pixel-button pixel-button-paper" onClick={()=>downloadCsv("學生帳戶名單範本.csv",[["email","班別","學號","姓名"],["example@ctshkpcc.edu.hk","1A","01","示例學生"]])}>下載 CSV 範本</button><button disabled={busy} className="pixel-button pixel-button-paper" onClick={()=>void run(async()=>{setPlan([]);await refresh();})}>重新讀取名單</button></div>
 <label className="my-4 block">讀取 CSV<input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{if(file.size>1000000)throw new Error("CSV 不可超過 1 MB。");setCsv(await file.text());setPlan([]);});}}/></label>
 <label>或貼上 CSV<textarea className="comic-input my-3 block min-h-28 w-full" value={csv} disabled={busy} onChange={e=>{setCsv(e.target.value);setPlan([]);}}/></label>
 <button disabled={busy} className="pixel-button pixel-button-paper" onClick={()=>void run(async()=>preview())}>檢查及預覽名單</button>
 {!!plan.length&&<div className="my-4 border-2 p-4"><p>將核准／更新 {plan.length} 人：</p><ul className="max-h-52 overflow-auto">{plan.map(p=><li key={p.id}>{p.row.email} → {p.row.className} · {p.row.studentNo} · {p.row.name}（{p.existing?"更新現有紀錄":"新增"}）</li>)}</ul><button disabled={busy} className="pixel-button pixel-button-teal mt-3" onClick={()=>void run(commit)}>確認匯入以上名單</button></div>}
 <h3 className="display-title mt-8 text-xl">連結校外 Gmail</h3><p className="my-2">先在名單建立學生，再把私人 Gmail 連到同一紀錄。原帳戶仍可使用；需要取消時，按下方「停用」。</p>
 <form className="grid gap-3" onSubmit={e=>{e.preventDefault();void run(async()=>{const clean=email.trim().toLowerCase();if(!/^[^/\s@]+@gmail\.com$/.test(clean)||clean===OWNER_EMAIL)throw new Error("請輸入學生的 Gmail，不可使用管理帳戶。");const previous=access.find(a=>a.email===clean);if(previous&&previous.studentId!==sid)throw new Error("此 Gmail 已對應另一名學生，請先核對身份，不能直接覆蓋。");await link(clean,sid,true);setEmail("");setNotice("已核准 Gmail，角色及進度共用同一份紀錄。");});}}>
 <label>學生 Gmail<input required type="email" className="comic-input block w-full" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>對應學生<select required className="comic-input block w-full" value={sid} onChange={e=>setSid(e.target.value)}><option value="">請選擇</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.profile.className} · {p.profile.studentNo} · {p.profile.name}</option>)}</select></label><button disabled={busy} className="pixel-button pixel-button-gold">核准並連結</button></form>
 {notice&&<p role="status" className="my-4 border-2 p-3">{notice}</p>}
 <ul className="mt-5 max-h-96 overflow-auto">{access.map(a=>{const p=profiles.find(p=>p.id===a.studentId)?.profile;return <li key={a.email} className="my-2 flex flex-wrap gap-3"><span>{a.email} → {p?`${p.className} · ${p.studentNo} · ${p.name}`:"紀錄不存在"} · {a.enabled?"已核准":"已停用"}</span><button disabled={busy} className="underline" onClick={()=>void run(async()=>link(a.email,a.studentId,!a.enabled))}>{a.enabled?"停用":"恢復"}</button></li>;})}</ul></section>;
}

